// swift-tools-version: 5.7
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

//let differenceKit = Target.binaryTarget(name: "DifferenceKit", path: "XCFrameworks/DifferenceKit.xcframework")
//let nuke = Target.binaryTarget(name: "Nuke", path: "XCFrameworks/Nuke.xcframework")

let package = Package(
    name: "AppPackage",
    products: [
        .library(
            name: "Umbrella",
            targets: ["Umbrella"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        .target(name: "Umbrella", dependencies: [
            "Action",
            "Actomaton",
//            "ActomatonUI",
//            "ActomatonStore",
//            "ActomatonDebugging",
            "Adjust",
            "Alamofire",
            "AWSCore",
            "AWSKinesis",
            "CombineCocoa",
            "CriteoPublisherSdk",
            "CropViewController",
            "DifferenceKit",
            "Differentiator",
            "FBAudienceNetwork",
            "FBSDKCoreKit",
            "FBSDKLoginKit",
            "FirebaseAnalytics",
            "FirebaseCore",
            "FirebaseCrashlytics",
            "FirebaseInstallations",
            "FirebaseMessaging",
            "FirebaseRemoteConfig",
            "FiveAd",
            "FiveGADAdapter",
            "FloatingPanel",
            "GoogleAnalytics",
            "Google-Mobile-Ads-SDK",
            "GoogleMobileAdsMediationFluct",
            "GoogleSignIn",
            "LineKit",
            "lottie-ios",
            "Nuke",
            "NukeExtensions",
            "NukeUI",
            "NVActivityIndicatorView",
            "Parchment",
//            "Realm",
//            "RealmSwift",
            "Repro",
            "Runtime",
            "RxCocoa",
            "RxCombine",
            "RxDataSources",
            "RxRelay",
            "RxSwift",
            "SherlockForms",
            "SherlockHUD",
            "SwiftyBeaver",
            "Unio",
            "GPUImage"
        ]),

        .binaryTarget(name: "Action", path: "XCFrameworks/Action.xcframework"),
        .binaryTarget(name: "Actomaton", path: "XCFrameworks/Actomaton.xcframework"),
//                .binaryTarget(name: "ActomatonUI", path: "XCFrameworks/ActomatonUI.xcframework"),
//                .binaryTarget(name: "ActomatonStore", path: "XCFrameworks/ActomatonStore.xcframework"),
//                .binaryTarget(name: "ActomatonDebugging", path: "XCFrameworks/ActomatonDebugging.xcframework"),
        
        .binaryTarget(name: "Adjust", path: "XCFrameworks/Adjust.xcframework"),
        .binaryTarget(name: "Alamofire", path: "XCFrameworks/Alamofire.xcframework"),
        .binaryTarget(name: "AWSCore", path: "XCFrameworks/AWSCore.xcframework"),
        .binaryTarget(name: "AWSKinesis", path: "XCFrameworks/AWSKinesis.xcframework"),
        .binaryTarget(name: "CombineCocoa", path: "XCFrameworks/CombineCocoa.xcframework"),
        .binaryTarget(name: "CriteoPublisherSdk", path: "XCFrameworks/CriteoPublisherSdk.xcframework"),
        .binaryTarget(name: "CropViewController", path: "XCFrameworks/CropViewController.xcframework"),
        .binaryTarget(name: "DifferenceKit", path: "XCFrameworks/DifferenceKit.xcframework"),
        .binaryTarget(name: "Differentiator", path: "XCFrameworks/Differentiator.xcframework"),
        .binaryTarget(name: "FBAudienceNetwork", path: "XCFrameworks/FBAudienceNetwork.xcframework"),
        .binaryTarget(name: "FBSDKCoreKit", path: "XCFrameworks/FBSDKCoreKit.xcframework"),
        .binaryTarget(name: "FBSDKLoginKit", path: "XCFrameworks/FBSDKLoginKit.xcframework"),
        .binaryTarget(name: "FirebaseAnalytics", path: "XCFrameworks/FirebaseAnalytics.xcframework"),
        .binaryTarget(name: "FirebaseCore", path: "XCFrameworks/FirebaseCore.xcframework"),
        .binaryTarget(name: "FirebaseCoreKit", path: "XCFrameworks/FirebaseCoreKit.xcframework"),
        .binaryTarget(name: "FirebaseCrashlytics", path: "XCFrameworks/FirebaseCrashlytics.xcframework"),
    
        .binaryTarget(name: "FirebaseInstallations", path: "XCFrameworks/FirebaseInstallations.xcframework"),
        .binaryTarget(name: "FirebaseMessaging", path: "XCFrameworks/FirebaseMessaging.xcframework"),
        .binaryTarget(name: "FirebaseRemoteConfig", path: "XCFrameworks/FirebaseRemoteConfig.xcframework"),
        .binaryTarget(name: "FiveAd", path: "XCFrameworks/FiveAd.xcframework"),
        .binaryTarget(name: "FiveGADAdapter", path: "XCFrameworks/FiveGADAdapter.xcframework"),
        .binaryTarget(name: "FloatingPanel", path: "XCFrameworks/FloatingPanel.xcframework"),
        .binaryTarget(name: "GoogleAnalytics", path: "XCFrameworks/GoogleAnalytics.xcframework"),
        .binaryTarget(name: "Google-Mobile-Ads-SDK", path: "XCFrameworks/Google-Mobile-Ads-SDK.xcframework"),
        .binaryTarget(name: "GoogleMobileAdsMediationFluct", path: "XCFrameworks/GoogleMobileAdsMediationFluct.xcframework"),
        .binaryTarget(name: "GoogleSignIn", path: "XCFrameworks/GoogleSignIn.xcframework"),
        .binaryTarget(name: "LineKit", path: "XCFrameworks/LineKit.xcframework"),
        .binaryTarget(name: "lottie-ios", path: "XCFrameworks/lottie-ios.xcframework"),
        .binaryTarget(name: "Nuke", path: "XCFrameworks/Nuke.xcframework"),
        .binaryTarget(name: "NukeExtensions", path: "XCFrameworks/NukeExtensions.xcframework"),
        .binaryTarget(name: "NukeUI", path: "XCFrameworks/NukeUI.xcframework"),
        .binaryTarget(name: "NVActivityIndicatorView", path: "XCFrameworks/NVActivityIndicatorView.xcframework"),
        .binaryTarget(name: "Parchment", path: "XCFrameworks/Parchment.xcframework"),
//        .binaryTarget(name: "Realm", path: "XCFrameworks/Realm.xcframework"),
//        .binaryTarget(name: "RealmSwift", path: "XCFrameworks/RealmSwift.xcframework"),
        .binaryTarget(name: "Repro", path: "XCFrameworks/Repro.xcframework"),
        .binaryTarget(name: "Runtime", path: "XCFrameworks/Runtime.xcframework"),
        .binaryTarget(name: "RxCocoa", path: "XCFrameworks/RxCocoa.xcframework"),
        .binaryTarget(name: "RxCombine", path: "XCFrameworks/RxCombine.xcframework"),
        .binaryTarget(name: "RxDataSources", path: "XCFrameworks/RxDataSources.xcframework"),
        .binaryTarget(name: "RxRelay", path: "XCFrameworks/RxRelay.xcframework"),
        .binaryTarget(name: "RxSwift", path: "XCFrameworks/RxSwift.xcframework"),
        .binaryTarget(name: "SherlockForms", path: "XCFrameworks/SherlockForms.xcframework"),
        .binaryTarget(name: "SherlockHUD", path: "XCFrameworks/SherlockHUD.xcframework"),
        .binaryTarget(name: "SwiftyBeaver", path: "XCFrameworks/SwiftyBeaver.xcframework"),
        .binaryTarget(name: "Unio", path: "XCFrameworks/Unio.xcframework"),


        

//        .binaryTarget(name: "GoogleAppMeasurement", path: "XCFrameworks/GoogleAppMeasurement.xcframework"),
//        .binaryTarget(name: "GoogleTagManager", path: "XCFrameworks/GoogleTagManager.xcframework"),
        .binaryTarget(name: "GPUImage", path: "XCFrameworks/GPUImage.xcframework"),
        .binaryTarget(name: "GoogleMobileAdsMediationFacebook", path: "XCFrameworks/GoogleMobileAdsMediationFacebook.xcframework"),
        .binaryTarget(name: "CustomDump", path: "XCFrameworks/CustomDump.xcframework"),
        .binaryTarget(name: "XCTestDynamicOverlay", path: "XCFrameworks/XCTestDynamicOverlay.xcframework"),
        .binaryTarget(name: "CasePaths", path: "XCFrameworks/CasePaths.xcframework"),
        .binaryTarget(name: "GoogleUtilities", path: "XCFrameworks/GoogleUtilities.xcframework"),
    ]
)
